### ISSUE TITLE
Can native crypto packages be supported?

### ISSUE THREAD

**Issue by 5idu** [dop251/goja_nodejs#74]
### problem background

i have install a node package `[uuid](https://www.npmjs.com/package/uuid)`, the  uuid package using native package `crypto`, when i run script bellow, a error has occur: 
GoError: Invalid module
        at github.com/dop251/goja_nodejs/require.(*RequireModule).require-fm (native)
        at node_modules/uuid/dist/rng.js:8:45(22)
        at github.com/dop251/goja_nodejs/require.(*RequireModule).require-fm (native)
        at node_modules/uuid/dist/v1.js:8:42(22)
        at github.com/dop251/goja_nodejs/require.(*RequireModule).require-fm (native)
        at node_modules/uuid/dist/index.js:61:40(116)
        at github.com/dop251/goja_nodejs/require.(*RequireModule).require-fm (native)
        at <eval>:18:19(13)

```js
const uuid = require('uuid');
console.log(uuid.v4());
```

**Comment by dop251** [comment]
A quick look shows that module should work without native support. I might be wrong but you could try registering an empty crypto module because it still needs to import it.

Having said that, I have a partial implementation which I plan to publish as a separate module, because I don't won't to bring extra dependencies to goja_nodejs.

**Comment by 5idu** [comment]
> A quick look shows that module should work without native support. I might be wrong but you could try registering an empty crypto module because it still needs to import it.
> 
> Having said that, I have a partial implementation which I plan to publish as a separate module, because I don't won't to bring extra dependencies to goja_nodejs.

I hope to have a built-in crypto module, just like the buffer module.
